baseURL = "http://ericleer.com"
languageCode = "en-us"
title = "EricLeer"
theme = "nofancy"

summarylength = 10

[params]
	# See themes/nofancy/static/highlight/styles for available options
	# i.e. "default", "github", "monokai".
	highlight="default"
	
	# Controls what items are listed in the top nav menu
	# "none", or "categories"
	# If you have too many categories to fit in the top nav menu, set this to "none"
	topmenu="hugo"
	
[author]
    name = "Eric Leerssen"
    github = "EricLeer"
    linkedin = "YOUR LINKEDIN ID"
    gaID = "YOUR Google Analytics Tracking ID"